version: '3'
services:
  galunos_interface:
    container_name: container-interface
    image: interface
    ports: 
      - "16001:16001"
    depends_on:
      - api
    links:
      - api
    
  api:
    container_name: container-api
    image: api-dados
    ports:
      - "16000:16000"
    depends_on:
      - mongo
    links:
      - mongo
      
  mongo:
    container_name: mongoDB
    image: mongo
    depends_on:
      - mongo-seed

  mongo-seed:
    image: mongo
    volumes:
      - ./contratos.json:/contratos.json
    command: mongoimport --host mongodb -d contratos -c contratos contratos.json --jsonArray
    
